### ISSUE TITLE
Generalization: Support for GitLab (and others)

### ISSUE THREAD

**Issue by asfaltboy** [daenney/err-repohook#4]
I implemented [a branch with initial support over here](https://github.com/asfaltboy/err-gitwebhook/tree/feature/gitlab-support).

@daenney let me know if you're interested in merging this into `err-githubhook`

**Comment by daenney** [comment]
Sounds good to me, but I'm not super happy with the rename to GitwebHook. It's potentially confusing with Gitweb: https://git.wiki.kernel.org/index.php/Gitweb. I'm not quite sure what to call it either though.

Other than that, +1

**Comment by asfaltboy** [comment]
How about repo-whatcher?
Or repohook?

I'm thinking that supporting bitbucket may take out `git` out of the
equation (since BB support hg and stuff)

**Comment by daenney** [comment]
I like the repohook, or vcshook.

**Comment by asfaltboy** [comment]
We could try to be funny and go for "repoman" or "capnhook" .. otherwise I think `repohook` is good; easier to say than `vcshook`

**Comment by daenney** [comment]
Lets stick with the obvious, repohook sounds good to me.

So we'd need to
- [x] Rename/move the repo
- [x] Update the prefix and docs that mention `!github`
- [ ] Get this reforked/moved too: https://github.com/errbotters/err-githubhook
- [ ] Update https://github.com/errbotio/errbot/wiki#107---githubhook
- [x] Merge your changes that add Gitlab support

Anything else?

**Comment by asfaltboy** [comment]
Update docs:
- mention supported providers github and gitlab
- invite PRs adding new providers

I currently did not implement message token validation in GitLab as you did in Github, simply didn't have a chance to play with a version that supports it yet.

**Comment by daenney** [comment]
Alright, I've done the rename so we should be good to go with getting your code changes in.

In order to further facilitate this I've added you as a collaborator to the repo. Go ahead, move fast, break a few things, have fun! 😄

**Comment by asfaltboy** [comment]
Thanks, this makes thing easier! I'm still not ready to merge but I'll push commits to update naming, adding a few other features.

Note: I updated the command root to `!repohook` rather than `!repo`, this is to avoid confusion with [`!repos *` built-in err commands](http://errbot.io/en/latest/user_guide/administration.html#installing-plugins)

**Comment by daenney** [comment]
That's a great point, thank you!

**Comment by asfaltboy** [comment]
OK, I think that's all I have time for today. I'd appreciate if you could take a look at PR #5 and let me know what you think.
