### ISSUE TITLE
Pulling out event library parsing code

### ISSUE THREAD

**Issue by srizzling** [daenney/err-repohook#8]
Is it possible to abstract the github event parsing into a seperate repo? I want to use the webhook feature and respond to events. I can't see a library, but did come across this.. Would that be possible?

**Comment by asfaltboy** [comment]
HI @srizzling thank you for your interest, however, I'm not sure what you're looking to change in daenney/err-repohook. 

The code to handle the generic parsing of an incoming request to the webhook [is here][1], and, to be honest, there's nothing to it besides a bit of (optional) validation and assigning `body = request.json`.

Feel free to create your own "provider" such as [`GithubHandlers`][2] and add methods to handle any messages you want. If you do end up writing something that is a generic fit to other github users, we would appreciate a Pull Request.

[1]: https://github.com/daenney/err-repohook/blob/master/repohook.py#L337
[2]: https://github.com/daenney/err-repohook/blob/master/providers.py#L42

**Comment by daenney** [comment]
There's already a [few Python libraries](https://www.google.com/search?q=python+github+webhook+validation) that can help you out when it comes to creating GitHub webhooks and handling the events.
  * https://github.com/carlos-jenkins/python-github-webhooks
  * https://github.com/razius/github-webhook-handler
  * https://github.com/bloomberg/python-github-webhook

Don't any of those fit your needs?

**Comment by srizzling** [comment]
Kind of, I did want to have something where I could just use lambda functions, and not have to standup an instance for. The bloomberg one does seem it could be weaved to my will..
